-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 16:05:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema bdproyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdproyecto` ;

-- -----------------------------------------------------
-- Schema bdproyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdproyecto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `bdproyecto` ;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clientes` (
  `ClienteID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ClienteID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detalle_pedios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalle_pedios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detalle_pedios` (
  `Detalle_pedioID` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `precio_unitario` VARCHAR(45) NOT NULL,
  `total` DECIMAL(30) NOT NULL,
  `productos_ProductoID` INT NOT NULL,
  PRIMARY KEY (`Detalle_pedioID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `empleados` (
  `EmpleadoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL DEFAULT NULL,
  `Puesto` ENUM('administrador', 'vendedor') NULL DEFAULT NULL,
  `Fecha_contratacion` DATE NULL DEFAULT NULL,
  `Salario` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`EmpleadoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedidos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pedidos` (
  `PedidoID` INT NOT NULL AUTO_INCREMENT,
  `Fecha_pedido` DATE NULL DEFAULT NULL,
  `ClienteID` INT NULL DEFAULT NULL,
  `Estado_pedido` ENUM('pendiente', 'en_proceso', 'completado') NULL DEFAULT 'pendiente',
  `clientes_ClienteID` INT NOT NULL,
  PRIMARY KEY (`PedidoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pedidos_has_detalle_pedios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pedidos_has_detalle_pedios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pedidos_has_detalle_pedios` (
  `pedidos_PedidoID` INT NOT NULL,
  `detalle_pedios_Detalle_pedioID` INT NOT NULL,
  PRIMARY KEY (`pedidos_PedidoID`, `detalle_pedios_Detalle_pedioID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `productos` (
  `ProductoID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`ProductoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;


INSERT INTO productos (Nombre, Descripcion, Precio, Cantidad) 
VALUES 
('Llantas Michelin Pilot Sport 4S', 'Llantas de alto rendimiento para automóviles deportivos y de alto rendimiento. Ofrecen una excelente tracción y manejo en seco y mojado.', 299.99, 15),
('Aceite de Transmisión Mobil 1 ATF', 'Aceite de transmisión automática sintético de alto rendimiento. Proporciona una lubricación excepcional y protección contra el desgaste.', 39.99, 25),
('Batería de Automóvil Optima RedTop', 'Batería de arranque de alto rendimiento diseñada para proporcionar una potencia de arranque óptima en condiciones extremas. Ideal para vehículos todoterreno.', 199.99, 10),
('Kit de Correas de Distribución Gates TCKWP329', 'Kit completo de correa de distribución que incluye correa, tensor y bomba de agua. Proporciona un reemplazo completo y confiable de las correas de distribución.', 129.95, 20),
('Amortiguadores Bilstein B8 5100', 'Amortiguadores de gas de alto rendimiento diseñados para aplicaciones de levantamiento de vehículos. Ofrecen un manejo preciso y una mayor capacidad de carga.', 179.99, 18),
('Filtros de Aceite K&N HP-1002', 'Filtros de aceite de alto rendimiento diseñados para brindar una filtración excepcional y una alta capacidad de flujo. Ideales para aplicaciones de alto rendimiento.', 14.99, 30),
('Juego de Tapetes para Automóvil WeatherTech', 'Tapetes de goma moldeada a medida para proteger el interior del vehículo de la suciedad, el barro y la humedad. Fáciles de limpiar y duraderos.', 99.95, 12),
('Faros LED Auxbeam F16 Series', 'Faros LED de alta potencia con carcasa de aluminio resistente al agua y lente de policarbonato. Proporcionan una iluminación brillante y duradera para condiciones off-road.', 129.99, 22),
('Escape Deportivo Borla ATAK', 'Sistema de escape cat-back de alto rendimiento con diseño de sonido agresivo. Proporciona un aumento de potencia y un tono profundo y resonante.', 699.99, 8),
('Kit de Frenos de Disco Power Stop K2798-36', 'Kit completo de frenos de disco delanteros y traseros con rotores perforados y ventilados y pastillas de freno cerámicas de alto rendimiento.', 349.95, 15),
('Aceite de Motor Royal Purple HPS 5W-30', 'Aceite de motor completamente sintético formulado para ofrecer una protección superior y un rendimiento óptimo en motores de alto rendimiento.', 49.99, 35),
('Cargador de Batería NOCO Genius10', 'Cargador y mantenedor de batería completamente automático de 10 amperios para vehículos de 6 y 12 voltios. Ideal para mantener las baterías cargadas y en buen estado durante el almacenamiento.', 99.95, 20),
('Filtros de Aire K&N E-0644', 'Filtros de aire lavables y reutilizables diseñados para mejorar el flujo de aire y la eficiencia del motor. Ideales para aplicaciones de alto rendimiento.', 49.99, 28),
('Amortiguadores KYB Excel-G 344385', 'Amortiguadores de gas de reemplazo OEM diseñados para proporcionar un manejo suave y cómodo. Ideales para restauraciones y reparaciones de suspensión.', 64.99, 24),
('Líquido de Frenos DOT 4 Motul RBF 600', 'Líquido de frenos de alto rendimiento con punto de ebullición extremadamente alto. Ofrece una excelente resistencia al calentamiento y una respuesta de frenado constante.', 19.99, 40),
('Bujes de Suspensión Energy Suspension 9.11104', 'Bujes de suspensión de poliuretano de alta calidad diseñados para proporcionar una mejor respuesta de la dirección y una mayor durabilidad que los bujes de goma.', 29.99, 32),
('Filtro de Aire S&B Filters KF-1058', 'Filtro de aire de alto rendimiento con diseño de flujo de aire mejorado. Proporciona una filtración superior y una mejora en la respuesta del motor.', 59.99, 20),
('Lubricante de Cadenas Motul Chain Lube Road', 'Lubricante de cadenas de moto diseñado para condiciones de carretera. Proporciona una lubricación duradera y reduce el desgaste de la cadena y los piñones.', 9.99, 45),
('Bombillas LED AUXITO 7443', 'Bombillas LED de freno y señal de giro diseñadas para proporcionar una iluminación brillante y duradera. Compatible con una variedad de vehículos.', 19.99, 38),
('Kit de Respaldo Lumbar Everlasting Comfort', 'Cojín de respaldo lumbar ergonómico con soporte de espuma viscoelástica para aliviar el dolor de espalda y mejorar la postura. Ideal para viajes largos en automóvil.', 29.95, 18);



-- -----------------------------------------------------
-- Table `proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proveedores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proveedores` (
  `ProveedorID` INT NOT NULL AUTO_INCREMENT,
  `NombreProveedor` VARCHAR(100) NOT NULL,
  `Contacto` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(200) NOT NULL,
  `Telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ProveedorID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proveedores_has_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proveedores_has_productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proveedores_has_productos` (
  `proveedores_ProveedorID` INT NOT NULL,
  `productos_ProductoID` INT NOT NULL,
  PRIMARY KEY (`proveedores_ProveedorID`, `productos_ProductoID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proveedores_has_vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proveedores_has_vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proveedores_has_vendedor` (
  `proveedores_ProveedorID` INT NOT NULL,
  `vendedor_idvendedor` INT NOT NULL,
  PRIMARY KEY (`proveedores_ProveedorID`, `vendedor_idvendedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `Correo` VARCHAR(40) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `id_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vendedor` (
  `idvendedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Contacto` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Cedula` INT NOT NULL,
  PRIMARY KEY (`idvendedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;